name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to EC2
        run: |
          scp -i "cicd.pem" -o StrictHostKeyChecking=no -r ./ ubuntu@52.91.184.202:/var/www/html/mywebsite/
